Feat: Added Avatar Components
shuntzhere/shore-UI pull request #1
Opened 2022-01-31 17:51 UTC by shuntzhere

2022-02-01 14:32 UTC, theprogrammerinyou requested changes
Please do the needful.

2022-02-01 14:32 UTC, theprogrammerinyou commented on avatar.html
> +      <br />
This <br /> tag is not required, as div is already a block element.

2022-02-01 14:32 UTC, theprogrammerinyou commented on components/avatar.css
> +h1 {
Have the typographies in typography.css file as base file and then if you want to overwrite you can write it here, but its better not to overwrite.

2022-02-01 14:32 UTC, theprogrammerinyou commented on components/avatar.css
> +.avatar.sm {
Have these as well in root file.

2022-02-03 17:43 UTC, Sameony commented on main.css
> +.flex {
Redundant code, .flex redeclared, Line no.10

2022-02-03 17:46 UTC, Sameony reviewed
Suggesting Minor Adjustments

2022-02-03 17:46 UTC, Sameony commented on main.css
> +.xxl {
Avoid Ambiguous class names

2022-02-04 11:45 UTC, shuntzhere commented on main.css
> +.flex {
Yeah, it's updated now.

2022-02-04 11:45 UTC, shuntzhere commented on main.css
> +.xxl {
Yes, will change them.

2022-02-04 11:48 UTC, shuntzhere commented on components/avatar.css
> +.avatars__container {
Yes,  this is updated now.

2022-02-04 11:48 UTC, shuntzhere commented on components/avatar.css
> +h1 {
Moved all to their specific files now.

2022-02-04 11:48 UTC, shuntzhere commented on components/avatar.css
> +.avatar.sm {
Done.

2022-02-06 05:07 UTC, Sameony approved these changes

2022-02-06 05:09 UTC, theprogrammerinyou approved these changes

2022-02-06 17:25 UTC, merged